#!/usr/bin/env python3
"""Generate Porygonal's Terrarium renderer adapter from its Dramatic Shape one.

Porygonal ("Porygonal - Overworld Characters", CurlyG004) does not draw
anything itself.  It detects ONE supported 3D renderer mod and swaps its
character cards for 3D models through that renderer's own draw calls, using a
per-renderer adapter in `renderers/<mod>/<mod>_adapter.lua`.  Every adapter
detects by exact mod id, so a fork needs its own file -- BATTLE_ART_VOXEL_FORK,
also a Dramatic Shape fork, has one for exactly this reason.

Terrarium is a Dramatic Shape fork too, so its adapter is that adapter with a
handful of edits.  Copying 4k lines by hand and re-diffing them on every
Porygonal release is the thing this script exists to avoid: it applies the
edits below to upstream's file, and ASSERTS each one matched the expected
number of times.  A Porygonal release that reshapes one of these call sites
fails the generator loudly instead of silently producing an adapter that
half-works.

    python make_adapter.py  [--porygonal <path to an installed Porygonal>]

Writes renderers/terrarium/terrarium_adapter.lua next to this script.

The four edits that are not cosmetic
------------------------------------

Terrarium drifted from the Dramatic Shape 1.8.2 the upstream adapter was
validated against.  Three public functions grew a parameter, and one module
never existed here:

  Voxel3D.draw(mesh, texture, model, pull, sunModel, sway)
      `sway` is the wind's reach at the top of the mesh, and Voxel3D sends it
      on EVERY draw so a swaying pass cannot leak into the terrain after it.
      An adapter that wraps draw with five parameters therefore pins sway to
      zero for the whole frame -- grass, trees and the battle scene's grass
      all stop moving, with no error anywhere.

  SpriteBillboards.mesh(def, frame, cut)
      `cut` is how many pixels of the feet are hidden: the waterline for a
      swimming roamer, the cut tall grass and settled snow make for anybody
      standing in them.  Dropped, a swimming mon stands on the pond.

  VoxelScene.render(state, w, h, vw, vh, paletteFor)
      Upstream's wrapper already forwards a 7th `eyes` argument.  Terrarium
      ignores it, so this one needs no edit -- listed here because it is the
      other signature worth checking on a re-sync.

  FirstPerson
      Terrarium has no first-person mode and ships no such module, and its
      V.require raises on a missing one.  Every USE of FirstPerson in the
      adapter is already nil-guarded, so only the require needs softening.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "renderers", "terrarium", "terrarium_adapter.lua")

DEFAULT_SOURCES = [
    # an installed Porygonal in the PC build
    r"C:\Users\breno\Downloads\GBA\Quiver-Windows-x64\Apps"
    r"\PokemonRedBlueYellow-Gen1RecompProject-Recomp\mods"
    r"\PORYGONAL_OVERWORLD_CHARACTERS",
]

REL_SOURCE = os.path.join(
    "renderers", "dramatic_shape", "dramatic_shape_adapter.lua")

HEADER = """\
----------------------------------------------------------------
-- Porygonal - Terrarium renderer adapter
--
-- GENERATED.  Do not edit this file directly: it is produced by
-- Terrarium's compat/porygonal/make_adapter.py from Porygonal's own
-- renderers/dramatic_shape/dramatic_shape_adapter.lua, and any hand edit
-- is lost on the next re-sync.  Change the generator instead.
--
-- Derived from Porygonal - Overworld Characters (CurlyG004), GPL-3.0.
-- This file is likewise GPL-3.0.  Terrarium only carries it so the pair
-- works before the adapter lands upstream.
--
-- Terrarium is a Dramatic Shape Voxel Mod fork, so the integration is
-- upstream's.  What differs is three public signatures Terrarium grew
-- after Dramatic Shape 1.8.2 -- Voxel3D.draw's `sway`, and
-- SpriteBillboards.mesh/shadowQuad's `cut` -- which this adapter forwards
-- rather than truncating, and FirstPerson, which Terrarium does not have.
----------------------------------------------------------------

"""

# Each edit is (description, needle, replacement, expected occurrences).
EDITS = [
    (
        "adapter table name",
        "local DramaticShapeAdapter = {}",
        "local TerrariumAdapter = {}",
        1,
    ),
    (
        "adapter table references",
        "DramaticShapeAdapter.",
        "TerrariumAdapter.",
        3,
    ),
    (
        "return value",
        "return DramaticShapeAdapter",
        "return TerrariumAdapter",
        1,
    ),
    (
        "target mod id (info block, detect, initialize)",
        '"DRAMATIC_SHAPE"',
        '"TERRARIUM"',
        3,
    ),
    (
        "target mod display name",
        'name = "Dramatic Shape Voxel Mod",',
        'name = "Terrarium (a Dramatic Shape Voxel Mod fork)",',
        1,
    ),
    (
        "validated target version",
        'validatedVersion = "1.8.2",',
        'validatedVersion = "1.36.0-beta",',
        1,
    ),
    # ---- the load-bearing ones -------------------------------------------
    (
        "FirstPerson is optional on Terrarium",
        """\
    local FirstPerson =
        V.require("FirstPerson")
""",
        """\
    -- Terrarium has no first-person mode and ships no FirstPerson module,
    -- and V.require RAISES on a missing one rather than returning nil --
    -- which would abort initialize() inside renderer_manager's pcall and
    -- read as "adapter could not be initialized".  Every use of this
    -- module below is already nil-guarded, so absence is a supported
    -- state; only the require needs to tolerate it.
    local okFirstPerson, FirstPerson =
        pcall(V.require, "FirstPerson")

    if not okFirstPerson then
        FirstPerson = nil
    end
""",
        1,
    ),
    (
        "SpriteBillboards.mesh forwards `cut`",
        """\
        SpriteBillboards.mesh =
            function(
                def,
                frame
            )

                return rememberBillboard(
                    originalBillboardMesh(
                        def,
                        frame
                    ),
                    def,
                    frame
                )
            end
""",
        """\
        -- `cut` is Terrarium's third parameter: how many pixels of the FEET
        -- are hidden.  A swimming roamer is cut at the waterline, and
        -- anybody standing in tall grass or settled snow is cut at what
        -- covers their boots.  Truncating the wrapper at two parameters
        -- would quietly draw every one of them at full height, standing on
        -- the water rather than in it.
        SpriteBillboards.mesh =
            function(
                def,
                frame,
                cut
            )

                return rememberBillboard(
                    originalBillboardMesh(
                        def,
                        frame,
                        cut
                    ),
                    def,
                    frame
                )
            end
""",
        1,
    ),
    (
        "SpriteBillboards.shadowQuad forwards `cut`",
        """\
        SpriteBillboards.shadowQuad =
            function(
                def,
                frame
            )

                return rememberBillboard(
                    originalShadowQuad(
                        def,
                        frame
                    ),
                    def,
                    frame
                )
            end
""",
        """\
        SpriteBillboards.shadowQuad =
            function(
                def,
                frame,
                cut
            )

                return rememberBillboard(
                    originalShadowQuad(
                        def,
                        frame,
                        cut
                    ),
                    def,
                    frame
                )
            end
""",
        1,
    ),
    (
        "Voxel3D.draw accepts `sway`",
        """\
        Voxel3D.draw =
            function(
                mesh,
                texture,
                model,
                pull,
                sunModel
            )
""",
        """\
        -- `sway` is Terrarium's sixth parameter: the wind's reach at the top
        -- of this mesh, in world pixels.  Voxel3D sends it on EVERY draw --
        -- deliberately, so a swaying pass can never leak into the terrain
        -- drawn after it -- which means a five-parameter wrapper does not
        -- merely miss the swaying passes, it pins the whole frame to zero.
        -- Grass, trees and the battle scene's grass would stand dead still
        -- with nothing logged anywhere.
        Voxel3D.draw =
            function(
                mesh,
                texture,
                model,
                pull,
                sunModel,
                sway
            )
""",
        1,
    ),
    (
        "Voxel3D.draw passes `sway` through",
        """\
                return originalVoxelDraw(
                    mesh,
                    texture,
                    model,
                    pull,
                    sunModel
                )
            end
""",
        """\
                return originalVoxelDraw(
                    mesh,
                    texture,
                    model,
                    pull,
                    sunModel,
                    sway
                )
            end
""",
        1,
    ),
    # ---- log lines the player reads --------------------------------------
    (
        "log: adapter name",
        "Dramatic Shape adapter:",
        "Terrarium adapter:",
        5,
    ),
    (
        "log: installed",
        '"Dramatic Shape Porygonal adapter installed"',
        '"Terrarium Porygonal adapter installed"',
        2,
    ),
    (
        "log: not installed",
        '"Dramatic Shape not installed"',
        '"Terrarium not installed"',
        1,
    ),
    (
        "log: API unavailable",
        '"Dramatic Shape API unavailable"',
        '"Terrarium API unavailable"',
        1,
    ),
    (
        "log: could not replace drawEntity",
        '"Dramatic Shape adapter could not',
        '"Terrarium adapter could not',
        2,
    ),
]


def find_source(explicit):
    candidates = [explicit] if explicit else DEFAULT_SOURCES
    for root in candidates:
        if not root:
            continue
        path = os.path.join(root, REL_SOURCE)
        if os.path.isfile(path):
            return path
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--porygonal", help="path to an installed Porygonal mod")
    args = ap.parse_args()

    source = find_source(args.porygonal)
    if not source:
        print("could not find dramatic_shape_adapter.lua; pass --porygonal "
              "<path to an installed Porygonal>", file=sys.stderr)
        return 2

    with open(source, "r", encoding="utf-8") as handle:
        text = handle.read()

    failures = []
    for label, needle, replacement, expected in EDITS:
        found = text.count(needle)
        if found != expected:
            failures.append(
                "  %-46s expected %d, found %d" % (label, expected, found))
            continue
        text = text.replace(needle, replacement)

    if failures:
        print("upstream adapter has moved -- these edits no longer apply:",
              file=sys.stderr)
        print("\n".join(failures), file=sys.stderr)
        print("\nsource: %s" % source, file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER + text)

    print("source : %s" % source)
    print("wrote  : %s (%d lines)" % (OUT, (HEADER + text).count("\n") + 1))
    print("edits  : %d applied" % len(EDITS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
